[build]
builder = "dockerfile"
dockerfilePath = "./FireStoreIoTAppointmentsService/Dockerfile"

[deploy]
startCommand = "dotnet", "FireStoreIoTAppointmentsService.dll"
restartPolicyType = "always"
healthcheckPath = "/health"